# -*- coding: utf-8 -*-
"""ATM project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15YWgwXI_2Qekl8CX3LRO3AhNTPAz57KG
"""

Atm_card = "card"
print("Your are Infront of Atm Machine")
print("Insert your Card")
pin = int(input("Enter your Pin"))
money = int(input("Enter your Amount"))
Temp = 0
for i in range(1,2):
  if(Atm_card=="card")&(pin==1234):
    if i==1:
      while Temp<=money:
        print("Count",Temp,"Total Amount",money)
        Temp=Temp+1000
      print("Take your money",money,"Rupees")
    else:
      print("only one attempt is possible")
  elif(Atm_card=="card")|(pin==1234):
    print("Any one value is wrong")
  else:
    print("Both values are wrong")

  print("Thank you for use")